// @ts-nocheck
/* eslint-disable */

// This file is auto-generated by Studio. Do not edit it manually.

import type { FC, SVGProps } from 'react';

export const IconBrandTailwind: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 256 256"
    {...props}
  >
    <path
      fill="currentColor"
      d="M128 0C57.31 0 0 57.31 0 128s57.31 128 128 128s128-57.31 128-128S198.69 0 128 0m-42.662 106.667c-11.777 0-21.332-9.555-21.332-21.334c0-11.778 9.555-21.333 21.332-21.333c11.778 0 21.333 9.555 21.333 21.333c0 11.779-9.555 21.334-21.333 21.334m85.333 0c-11.778 0-21.334-9.555-21.334-21.334c0-11.778 9.556-21.333 21.334-21.333s21.333 9.555 21.333 21.333c0 11.779-9.555 21.334-21.333 21.334m-42.663 64c-23.555 0-42.667-19.11-42.667-42.666c0-23.555 19.112-42.667 42.667-42.667c23.555 0 42.666 19.112 42.666 42.667c0 23.556-19.111 42.666-42.666 42.666"
    />
  </svg>
);
export const IconBrandNextjs: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 256 256"
    {...props}
  >
    <path
      fill="currentColor"
      d="M128 0C57.31 0 0 57.31 0 128s57.31 128 128 128s128-57.31 128-128S198.69 0 128 0m42.667 213.333H128V42.667h21.333v128h21.334zM85.333 42.667l85.334 103.244V42.667z"
    />
  </svg>
);
export const IconBrandReact: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m-2.28 15.244a2.533 2.533 0 0 1-3.66-.086a.5.5 0 0 1 .634-.772a1.533 1.533 0 0 0 2.21.053c.27-.24.43-.586.444-.954c.026-.648-.36-1.122-.98-1.39c-.68-.29-1.57-.52-2.58-.69c-1.8-.3-3.26-1.08-3.9-2.23c-.7-.9-1.04-2.2-1.04-3.93C1.82 4.477 4.293 2 7.18 2c1.58 0 2.94.63 3.96 1.63a.5.5 0 0 1-.72.69a3.79 3.79 0 0 0-3.23-1.32c-1.9 0-3.36 1.49-3.36 3.51c0 1.95 1.13 2.95 2.45 3.42c.86.3 1.77.54 2.63.74c1.9.44 3.4 1.16 4.02 2.37c.73 1.25 1.05 2.68 1.05 4.36c.01 3.2-2.39 5.39-5.63 5.39a4.73 4.73 0 0 1-4.08-2.03a.5.5 0 0 1 .84-.54a3.73 3.73 0 0 0 3.24 1.63c2.18 0 3.73-1.4 3.73-3.64c.02-2.3-1.34-3.5-3.08-4.03"
    />
    <ellipse
      fill="currentColor"
      cx={12}
      cy={12}
      rx={4}
      ry={9.5}
      transform="rotate(60 12 12)"
    />
    <ellipse
      fill="currentColor"
      cx={12}
      cy={12}
      rx={4}
      ry={9.5}
      transform="rotate(120 12 12)"
    />
  </svg>
);
export const IconBrandTypescript: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m6 15.5h-3.5v-1.25a2.25 2.25 0 0 0-2.25-2.25h-1.5a2.25 2.25 0 0 0-2.25 2.25V17.5H6.5v-11h8v1.5h-6.5v3h5v1.5h-5v3.5h1.5a.75.75 0 0 1 .75.75V16h2a.75.75 0 0 1 .75-.75a.75.75 0 0 1 .75.75h2.5v-1.5h-1v-4h1z"
    />
  </svg>
);
export const IconBrandJavascript: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m5.5 13.5h-1a.5.5 0 0 1-.5-.5v-1.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1.5a.5.5 0 0 1-.5.5m-3 0h-1a.5.5 0 0 1-.5-.5v-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5m-4.5 0h-2c-.28 0-.5-.22-.5-.5v-5a.5.5 0 0 1 .5-.5h2c.28 0 .5.22.5.5v1h-1.5v1.5h1v1h-1v1.5h1.5v1Z"
    />
  </svg>
);
export const IconBrandHtml5: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m0 16l-4-1.25V9h8v5.75zM15 10h-6v1h6zm-6 2h6v1h-6z"
    />
  </svg>
);
export const IconBrandCss3: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m4.5 4l-1.5 6h-6l-1-4h8.5M8.5 18l-1-4h11l-1 4z"
    />
  </svg>
);
export const IconBrandNodejs: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m5.09 15.5l-3.37-2.02c-.22-.13-.35-.38-.35-.64v-3.7l-2.75 1.57v2.11c0 .26-.13.51-.35.64l-3.37 2.02c-.38.22-.85-.04-.85-.48V8.52c0-.44.47-.7.85-.48l3.37 2.02c.22.13.35.38.35.64v3.7l2.75-1.57V8.52c0-.44.47-.7.85-.48l3.37 2.02c.38.22.38.74 0 .96L14.74 13l3.35-1.93c.38-.22.85.04.85.48V15c0 .44-.47.7-.85.48"
    />
  </svg>
);
export const IconBrandFirebase: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m-2.28 3.81L12 4.04l5.37 12.15l-3.09-1.8zM4.5 12l3.09-7.07l6.69 3.86z"
    />
  </svg>
);
export const IconBrandPostgresql: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m4.5 10.5h-1.5V18h-2v-5.5H10v-2h3v-3h2v3h1.5zM8 7h2v5H8z"
    />
  </svg>
);
export const IconBrandGraphql: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8s8 3.59 8 8s-3.59 8-8 8"
    />
    <path
      fill="currentColor"
      d="M12 4.5a.5.5 0 0 0-.5.5v14a.5.5 0 0 0 .5.5s.5-.224.5-.5V5a.5.5 0 0 0-.5-.5m-6.5 6a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5H7l5 5l5-5h1.5a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5H17l-5 5z"
    />
  </svg>
);
export const IconBrandGit: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m6.5 13.5l-4-4v-3h-2v3l-4 4h-2l6-6l6 6z"
    />
  </svg>
);
export const IconBrandGithub: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.166 6.84 9.49c.5.09.68-.217.68-.482c0-.237-.008-.868-.013-1.703c-2.782.605-3.369-1.343-3.369-1.343c-.454-1.157-1.11-1.466-1.11-1.466c-.908-.62.069-.608.069-.608c1.003.07 1.531 1.032 1.531 1.032c.892 1.53 2.341 1.088 2.91.832c.092-.647.35-1.088.636-1.338c-2.22-.253-4.555-1.113-4.555-4.951c0-1.093.39-1.988 1.03-2.688c-.103-.253-.446-1.272.098-2.65c0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.82c.85.004 1.705.115 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027c.546 1.379.203 2.398.1 2.65c.64.7 1.028 1.595 1.028 2.688c0 3.848-2.338 4.695-4.566 4.942c.359.308.678.92.678 1.852c0 1.338-.012 2.419-.012 2.747c0 .267.18.577.688.48A10.001 10.001 0 0 0 22 12c0-5.523-4.477-10-10-10"
    />
  </svg>
);
export const IconBrandDocker: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m4.5 12.5h-9v-2h9zM8 11V9h2v2zm3 0V9h2v2zm3 0V9h2v2z"
    />
  </svg>
);
export const IconBrandFigma: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m-1.5 5.5a2 2 0 1 1 0 4H12v-4zM12 9.5a2 2 0 1 1 0 4h-1.5v-4zm-1.5 6a2 2 0 1 1 0 4H9.5a2 2 0 0 1-2-2v-2z"
    />
    <path fill="currentColor" d="M14.5 7.5a2 2 0 1 1 0 4h-2.5v-4z" />
    <path fill="currentColor" d="M14.5 13.5a2 2 0 1 1 0 4v-2a2 2 0 0 1-2-2h2z" />
  </svg>
);
export const IconBrandVscode: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m7 12.5l-5 5h-1.5L7 14v-4l5.5-5.5H14l5 5z"
    />
    <path fill="currentColor" d="m14 14.5l-3-3l3-3l3 3z" />
  </svg>
);
export const IconBrandVercel: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10s10-4.477 10-10S17.523 2 12 2m0 16l-6-10h12z"
    />
  </svg>
);
export const IconBrandLinkedin: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="currentColor"
      d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zm-11 5H5v11h3zm-1.5-2.5a1.5 1.5 0 1 0 0-3a1.5 1.5 0 0 0 0 3M17 8h-2c-1.11 0-2 .89-2 2v2h-1v2h1v5h3v-5h1.5v-2H15v-1.5c0-.28.22-.5.5-.5H17z"
    />
  </svg>
);
export const IconPnpm: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 256 256"
    {...props}
  >
    <path
      fill="#F9AD00"
      d="M0 0h256v256H0V0z"
    />
    <path
      fill="#4E4E4E"
      d="M32 32h64v64H32V32zm0 128h64v64H32v-64zm128-96h64v64h-64V64zm-96 32h64v64H64v-64z"
    />
  </svg>
);
export const IconExpress: FC<SVGProps<SVGSVGElement>> = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    {...props}
  >
    <path 
      fill="currentColor" 
      d="M4.2 10.11h6.47a.2.2 0 0 0 .19-.31L9.43 6.3a.2.2 0 0 1 .34-.14l2.12 2.12a.2.2 0 0 1 0 .28l-2.12 2.12a.2.2 0 0 1-.34-.14l-1.42-3.5a.2.2 0 0 0-.19-.31H4.2a.2.2 0 0 1-.2-.2v-.58c0-.11.09-.2.2-.2h13.48l1.3-1.3a.2.2 0 0 0 0-.28l-.71-.71a.2.2 0 0 0-.28 0l-1.3 1.3H3.2a.2.2 0 0 0-.2.2V12a9.91 9.91 0 0 0 1.14 4.57l3.82 5.2a.2.2 0 0 0 .17.09h1.72a.2.2 0 0 0 .17-.09l-3.82-5.2A.2.2 0 0 1 6.2 16h13.6a.2.2 0 0 0 .2-.2v-.58a.2.2 0 0 0-.2-.2H9.2a.2.2 0 0 1-.17.09l-3.82 5.2a.2.2 0 0 0 .17.31h1.72a.2.2 0 0 0 .17-.09L11.23 16h8.57a.2.2 0 0 0 .2-.2v-.58a.2.2 0 0 0-.2-.2h-5.47a.2.2 0 0 0-.19.31l1.42 3.5a.2.2 0 0 1-.34.14l-2.12-2.12a.2.2 0 0 1 0-.28l2.12-2.12a.2.2 0 0 1 .34.14l-1.42 3.5a.2.2 0 0 0 .19.31h5.47a.2.2 0 0 0 .2-.2V12a.2.2 0 0 0-.2-.2h-1.48l-1.3-1.3a.2.2 0 0 1 0-.28l.71-.71a.2.2 0 0 1 .28 0l1.3 1.3H20.8a.2.2 0 0 1 .2.2v6.6a.2.2 0 0 1-.2.2h-1.6a.2.2 0 0 1-.2-.2v-2.6h-5.47a.2.2 0 0 0-.19.31l1.42 3.5a.2.2 0 0 1-.34.14l-2.12-2.12a.2.2 0 0 1 0-.28l2.12-2.12a.2.2 0 0 1 .34.14l-1.42 3.5a.2.2 0 0 0 .19.31h5.47a.2.2 0 0 0 .2-.2V12a.2.2 0 0 0-.2-.2h-1.48l-1.3-1.3a.2.2 0 0 1 0-.28l.71-.71a.2.2 0 0 1 .28 0l1.3 1.3H20.8a.2.2 0 0 1 .2.2v6.6a.2.2 0 0 1-.2.2h-1.6a.2.2 0 0 1-.2-.2v-2.6H8.11A9.87 9.87 0 0 0 2 12a9.91 9.91 0 0 0 2.2-6.09H3.2a.2.2 0 0 1-.2-.2v-.58c0-.11.09-.2.2-.2h15.48l1.3-1.3a.2.2 0 0 0 0-.28l-.71-.71a.2.2 0 0 0-.28 0l-1.3 1.3H4.2a.2.2 0 0 0-.2.2v.58c0 .11.09.2.2.2Z"
    />
  </svg>
);

const iconMap = {
  'next.js': IconBrandNextjs,
  react: IconBrandReact,
  typescript: IconBrandTypescript,
  javascript: IconBrandJavascript,
  html5: IconBrandHtml5,
  css3: IconBrandCss3,
  'tailwind css': IconBrandTailwind,
  'node.js': IconBrandNodejs,
  express: IconExpress,
  firebase: IconBrandFirebase,
  postgresql: IconBrandPostgresql,
  graphql: IconBrandGraphql,
  'git & github': IconBrandGit,
  docker: IconBrandDocker,
  figma: IconBrandFigma,
  'vs code': IconBrandVscode,
  vercel: IconBrandVercel,
  pnpm: IconPnpm,
  github: IconBrandGithub,
  linkedin: IconBrandLinkedin,
};

export const getIconForTechnology = (tech: string): FC<SVGProps<SVGSVGElement>> => {
  const normalizedTech = tech.toLowerCase();
  return iconMap[normalizedTech] || null;
};
